version: "3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - /data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    environment:
      - node.name=elasticsearch
      - http.port=9200
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /var/lib/elasticsearch
    ports:
      - "${ELASTIC_SEARCH_PORT}:${ELASTIC_SEARCH_PORT}"
  redis:
    image: "redis:latest"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "4000:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/backend/node_modules
      - ./backend:/app/backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo/
      - ELASTICSEARCH_URI=${ELASTIC_SEARCH_URL}
      - ELASTIC_SEARCH_PORT=${ELASTIC_SEARCH_PORT}
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/frontend/node_modules
      - ./frontend:/app/frontend